import type { Metadata } from "next";
import { Hind_Siliguri } from 'next/font/google';
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const bengaliFont = Hind_Siliguri({
  subsets: ['bengali'],
  weight: ['400', '600', '700'],
  variable: '--font-bengali',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bengaliFont.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
